Repository exercism/pharo-smalltalk, pull requests merged in 2024-02, with the labels that each got.

#605 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny

#608 roman-numerals: sync
  exercises/practice/roman-numerals/.docs/instructions.md
  exercises/practice/roman-numerals/.docs/introduction.md
  exercises/practice/roman-numerals/.meta/config.json
Labels: x:size/tiny

#609 Fix ci p11 p12
  .github/workflows/ci.yml
  README.md
  dev/src/BaselineOfExercism/BaselineOfExercism.class.st
  dev/src/ExercismDev/ExercismExerciseGenerator.class.st
  dev/src/ExercismDev/ExercismGenerator.class.st
  dev/src/ExercismPharo110/ExTonelWriter.class.st
  dev/src/ExercismPharo110/package.st
  dev/src/ExercismPharo120/ExercismSubmissionTest.extension.st
  dev/src/ExercismPharo120/package.st
  dev/src/ExercismPharo90/StDebugger.extension.st
  dev/src/ExercismPharo90/package.st
  dev/src/ExercismTests/ExercismExerciseTest.class.st
  dev/src/ExercismTests/ExercismGeneratorTest.class.st
  dev/src/ExercismTools/ExTonelWriter.class.st
  dev/src/ExercismTools/ExTonelWriter.extension.st
  dev/src/ExercismTools/ExercismCodeExporter.class.st
  dev/src/ExercismTools/ExercismExercise.class.st
  dev/src/ExercismTools/MCSnapshot.extension.st
Labels: bug, in progress, cleanup, CI

#611 610 all pharo tests pass even though i didnt solve the exercise
  dev/src/BaselineOfExercism/BaselineOfExercism.class.st
  dev/src/ExercismPharo110/Class.extension.st
  dev/src/ExercismPharo110/package.st
  dev/src/ExercismTestRunner/ExercismTest.extension.st
Labels: x:action/fix, x:module/test-runner, x:size/small
